/** The words for signing in and the account, loaded only with the parts that use them. */
export const accountText = {
  signIn: 'Sign in',
  signInWithGoogle: 'Sign in with Google',
  signedInAs: (email: string) => `Signed in as ${email}`,
  menu: 'Account',
  signOut: 'Sign out',
  synced: (when: string) => `Courses saved to your account ${when}`,
  syncing: 'Saving to your account…',
  offline: 'Offline. Changes go to your account when you’re back online.',
  syncError: 'Couldn’t reach your account. Folio will keep trying.',
  justNow: 'just now',
  minutesAgo: (n: number) => (n === 1 ? '1 minute ago' : `${n} minutes ago`),
  // Signing in.
  goingToGoogle: 'Taking you to Google…',
  finishing: 'Signing you in…',
  signedIn: 'You’re signed in. You can close this window.',
  failedTitle: 'Couldn’t sign you in',
  failed: 'Google’s answer couldn’t be checked. Try again.',
  cancelled: 'Sign-in was canceled.',
  unavailable: 'Signing in isn’t available here.',
  tryAgain: 'Try again',
  backToFolio: 'Back to Folio',
  sessionEnded: 'You were signed out. Sign in again to keep your courses in your account.',
  // The courses already on this device.
  offerTitle: 'Add these courses to your account?',
  offerLede: 'These courses are only in this browser. Courses in your account are there on any device you sign in on.',
  offerAdd: (n: number) => (n === 1 ? 'Add 1 course' : `Add ${n} courses`),
  offerKeep: 'Keep them on this device only',
  lessons: (n: number) => (n === 1 ? '1 lesson' : `${n} lessons`),
  // Conflicts.
  copyTitle: (title: string) => `${title} (this device)`,
  keptBoth: (title: string) => `“${title}” was also changed on another device. Both versions are kept: yours is now “${title} (this device)”.`,
  // Signing out.
  signOutTitle: 'Sign out?',
  signOutBody: 'Your courses stay in your account. This browser forgets them until you sign in again.',
  signOutUnsent: (n: number) => (n === 1 ? '1 course has changes that haven’t reached your account yet, and they would be lost. Go online and wait a moment, or sign out anyway.' : `${n} courses have changes that haven’t reached your account yet, and they would be lost. Go online and wait a moment, or sign out anyway.`),
  signOutAnyway: 'Sign out anyway',
  cancel: 'Cancel',
  // Settings.
  section: 'Account',
  lede: 'Signing in is optional. It keeps your courses in your account, so they’re on every device you sign in on. Your AI key never leaves this browser.',
  signedOutLede: 'You’re not signed in. Your courses are only in this browser.',
  deleteAccount: 'Delete my account and courses',
  deleteTitle: 'Delete your account?',
  deleteBody: 'This deletes your account and every course in it, from Folio’s servers and from this browser, and ends any Folio credits left in it. It can’t be undone. Courses only on this device stay.',
  deleteConfirm: 'Delete my account',
  deleted: 'Your account and its courses were deleted.',
};
