/**
 * What each example course under the composer writes into the box: a model brief. It names the students,
 * how many lessons and how long, what students should be able to do by the end, where they start, the
 * classroom, and how the course is assessed, because that is what makes a good course. Kept apart from the
 * interface copy so the first page doesn't carry it; it loads when the page is idle.
 */
export const EXAMPLE_BRIEFS: Record<string, string> = {
  'Fractions on a number line, grade 3, 4 lessons':
    'Fractions on a number line for grade 3: four 45-minute math lessons. By the end, students can place unit fractions and fractions like 3/4 and 5/8 on a number line, see that 2/4 and 1/2 name the same point, and compare two fractions using the line. They have used fraction strips but not number lines yet. Use hands-on activities, such as folding paper strips and a number line taped to the floor, and end with a short quiz I can grade quickly.',
  'The water cycle, grade 5, 3 lessons':
    'The water cycle for grade 5: three 50-minute science lessons. Students should be able to explain evaporation, condensation, precipitation and collection, and describe how the sun drives the cycle. Include one simple classroom experiment with a sealed plastic bag or a jar, a diagram students label themselves, and a short writing task where they follow one drop of water through the cycle. Several students are English learners, so give strong vocabulary support.',
  'Writing a personal narrative, grade 3, 6 lessons':
    'Personal narrative writing for grade 3: six 40-minute lessons that take students from choosing a small moment to a finished, revised story. Teach a strong beginning, telling events in order with transition words, adding feelings and details, and an ending that wraps up. Use short mentor texts, a planning organizer and peer feedback with a simple checklist. The final assignment is a one-page story, with a rubric I can share with families.',
  'Plant and animal life cycles, grade 2, 3 lessons':
    'Life cycles of plants and animals for grade 2: three 40-minute lessons. Students compare the life cycles of a bean plant, a butterfly and a frog, put the stages in order, and notice what all living things share: they are born, grow, reproduce and die. Include a bean-sprouting activity we can watch over two weeks, picture cards for sequencing, and a simple drawing-and-labeling check at the end.',
  'Multiplication strategies, grade 3, 5 lessons':
    'Multiplication strategies for grade 3: five 45-minute math lessons. Students know skip counting and have just met equal groups. Build from equal groups to arrays, repeated addition and the commutative property, then to using facts they know (doubles, fives, tens) to work out ones they don’t. Include games for practice, word problems about everyday situations, and a quiz on the 2s, 5s and 10s facts with one or two problems where students explain their strategy.',
  'Photosynthesis, grade 7, 3 lessons':
    'Photosynthesis for grade 7 life science: three 50-minute lessons, aligned to NGSS MS-LS1-6. Students should be able to explain how plants use light, water and carbon dioxide to make glucose and release oxygen, and use evidence from an investigation to support that explanation. Include a floating leaf disk or Elodea experiment we can run with basic lab supplies, a model students draw of where each input and output goes, and a quiz with some questions that ask them to read data.',
  'Solving linear equations, grade 9, 4 lessons':
    'Solving linear equations for grade 9 Algebra 1: four 50-minute lessons, from two-step equations to equations with variables on both sides, the distributive property and like terms, and equations with no solution or infinitely many. Show worked examples with the reasoning at each step and discuss common mistakes, such as sign errors and distributing to only one term. Give plenty of practice at rising difficulty, a warm-up to start each lesson and an exit ticket to end it.',
  'The French Revolution, grade 10, 6 lessons':
    'The French Revolution for grade 10 world history: six 50-minute lessons on its causes, the Estates-General and the storming of the Bastille, the Declaration of the Rights of Man, the Terror, and the rise of Napoleon. Students work with short primary-source excerpts, debate whether the Revolution achieved its goals, and write a short argumentative essay with a clear thesis and evidence. Include a rubric for the essay.',
  'Argumentative essays, grade 8, 6 lessons':
    'Writing argumentative essays for grade 8 English: six 45-minute lessons. Students learn to state a clear claim, support it with reasons and evidence from two short articles, answer a counterclaim, and organize a five-paragraph essay. Use a topic they care about, such as whether school should start later, and supply the two articles. Include a planning organizer, model paragraphs, a peer review session and a rubric for the final essay.',
  'Personal finance and credit, grade 12, 4 lessons':
    'Personal finance for grade 12: four 55-minute lessons on budgeting, how credit scores work, credit cards and interest, and student loans. Students should be able to build a monthly budget from a first-job paycheck, work out what a credit card balance costs over a year at a given rate, and compare two loan offers. Use realistic US numbers, a budgeting spreadsheet activity and case studies of young adults, and end with a practical assignment rather than a test.',
  'Intro to ethics, first-year university, 8 seminars':
    'Introduction to ethics for first-year university students: eight 75-minute seminars. Cover consequentialism, deontology, virtue ethics and social contract theory, then apply them to two current questions, such as what we owe distant strangers and who is responsible when an AI system causes harm. Give each seminar discussion questions students prepare in advance. Grading: weekly reading responses 30%, participation 20%, and a final 2,000-word argumentative paper 50%, with a rubric.',
  'Microeconomics for undergraduates, 10 lectures':
    'Principles of microeconomics for undergraduates: ten 75-minute lectures on supply and demand, elasticity, consumer choice, costs of production, perfect competition, monopoly, and market failures such as externalities. Students should be able to draw and read the graphs and solve short numerical problems. Include worked examples in every lecture, a problem set every two lectures, and a midterm and final drawn from the quiz bank. Use current, real-world examples.',
  'Calculus I for college freshmen, 10 lessons':
    'Calculus I for college freshmen: ten 50-minute lessons on limits and derivatives. Start with limits and continuity, then the definition of the derivative; the power, product, quotient and chain rules; and applications to rates of change and optimization. Many students are rusty on algebra and trigonometry, so build in quick reviews. Include worked examples, practice sets with answers, and quizzes that mix computation with one conceptual question.',
  'Climate science for undergraduates, 8 lectures':
    'Climate science for undergraduates who are not science majors: eight 75-minute lectures on the greenhouse effect, the carbon cycle, the evidence that the climate is changing (ice cores, temperature records), climate models and their uncertainty, impacts, and mitigation and adaptation. Students should be able to read a climate graph and explain the evidence to a friend. Use real NASA and NOAA data, short in-class activities, discussion questions, and a final project on one local climate impact.',
  'Research methods, master’s seminar, 12 weeks':
    'Research methods for first-year master’s students in psychology: twelve weekly 120-minute seminars. Cover research questions and hypotheses, experimental and quasi-experimental designs, sampling, validity and reliability of measures, research ethics and IRB review, and pre-registration. Each seminar discusses one published study and includes a hands-on design exercise. Students build a full research proposal across the term, submitted in three graded parts, each with a rubric.',
};
