import type { MaterialKind } from './materials';
import type { Language } from './schema';

/**
 * Words that appear inside materials. They follow the course language, not
 * the interface language, because the documents are for the classroom.
 */

const en = {
  materials: {
    map: 'Course map',
    syllabus: 'Syllabus',
    plan: 'Lesson plans',
    slides: 'Slide decks',
    assignments: 'Assignments',
    rubrics: 'Rubrics',
    discussions: 'Discussions',
    quiz: 'Quiz & exam bank',
    study: 'Study guides',
    faq: 'Course FAQ',
  } satisfies Record<MaterialKind, string>,
  lesson: (n: number) => `Lesson ${n}`,
  lessons: 'Lessons',
  /** A table column in which each row is one lesson. */
  lessonColumn: 'Lesson',
  minutes: (n: number) => `${n} min`,
  audience: 'Audience',
  length: 'Length',
  lengthValue: (lessons: number, minutes: number) => `${lessons} lessons · ${minutes} minutes each`,
  subject: 'Subject',
  objectives: 'Objectives',
  whatYouLearn: 'What you will learn',
  schedule: 'Schedule',
  focus: 'Focus',
  reading: 'Reading',
  beforeClass: 'Before class',
  assessment: 'How learning is assessed',
  gradeItem: 'Component',
  weight: 'Weight',
  total: 'Total',
  weightsOff: (total: string) => `These weights add up to ${total}, not 100%.`,
  quizzesLine: (n: number, per: number) => `${n} short quizzes, about ${per} questions each`,
  assignmentLine: (title: string, n: number) => `${title} (lesson ${n})`,
  discussionsLine: (n: number) => `Class discussions in ${n} lessons`,
  policies: 'Class policies',
  keyIdeas: 'Key ideas',
  vocabulary: 'Vocabulary',
  time: 'Time',
  activity: 'Activity',
  details: 'What happens',
  teacherNote: 'Teacher note',
  steps: 'Steps',
  gradedWith: (title: string) => `Graded with: ${title}`,
  criterion: 'Criterion',
  followUps: 'Follow-up questions',
  answerKey: 'Answer key',
  answer: 'Answer',
  why: 'Why',
  checkYourself: 'Check yourself',
  overview: 'Overview',
  coveredIn: 'Taught in',
  assessedBy: 'Assessed by',
  questionsCount: (n: number) => `${n} questions`,
  none: '—',
  studentCopy: 'Student copy',
  teacherCopy: 'Teacher copy',
  trueWord: 'True',
  falseWord: 'False',
  continued: (title: string) => `${title} (continued)`,
  points: (n: number) => `${n} pts`,
  general: 'General',
};

export type DocLabels = typeof en;

const zh: DocLabels = {
  materials: {
    map: '课程地图',
    syllabus: '教学大纲',
    plan: '教案',
    slides: '课件',
    assignments: '作业',
    rubrics: '评分量表',
    discussions: '课堂讨论',
    quiz: '测验与题库',
    study: '学习指南',
    faq: '课程问答',
  },
  lesson: (n) => `第 ${n} 课`,
  lessons: '课时',
  lessonColumn: '课',
  minutes: (n) => `${n} 分钟`,
  audience: '对象',
  length: '课时安排',
  lengthValue: (lessons, minutes) => `共 ${lessons} 课 · 每课 ${minutes} 分钟`,
  subject: '学科',
  objectives: '学习目标',
  whatYouLearn: '你将学到',
  schedule: '课程安排',
  focus: '重点',
  reading: '课前阅读',
  beforeClass: '课前阅读',
  assessment: '评价方式',
  gradeItem: '考核项目',
  weight: '占比',
  total: '合计',
  weightsOff: (total) => `各项占比合计为 ${total}，而不是 100%。`,
  quizzesLine: (n, per) => `${n} 次小测，每次约 ${per} 题`,
  assignmentLine: (title, n) => `${title}（第 ${n} 课）`,
  discussionsLine: (n) => `${n} 节课包含课堂讨论`,
  policies: '课堂规则',
  keyIdeas: '核心概念',
  vocabulary: '关键词',
  time: '时间',
  activity: '环节',
  details: '内容',
  teacherNote: '教师提示',
  steps: '步骤',
  gradedWith: (title) => `评分依据：${title}`,
  criterion: '评价维度',
  followUps: '追问',
  answerKey: '参考答案',
  answer: '答案',
  why: '解析',
  checkYourself: '自我检测',
  overview: '概要',
  coveredIn: '所在课时',
  assessedBy: '评价方式',
  questionsCount: (n) => `${n} 道题`,
  none: '—',
  studentCopy: '学生版',
  teacherCopy: '教师版',
  trueWord: '正确',
  falseWord: '错误',
  continued: (title: string) => `${title}（续）`,
  points: (n) => `${n} 分`,
  general: '通用',
};

export function docLabels(language: Language): DocLabels {
  return language === 'zh-CN' ? zh : en;
}
