import type { MaterialKind } from './materials';
import type { Language, SessionKind } from './schema';

/**
 * Words that appear inside materials. They follow the course language, not
 * the interface language, because the documents are for the classroom.
 */

const en = {
  materials: {
    map: 'Objectives & assessment',
    syllabus: 'Syllabus',
    plan: 'Lesson plans',
    slides: 'Slide decks',
    assignments: 'Assignments',
    rubrics: 'Rubrics',
    discussions: 'Discussions',
    quiz: 'Quiz & exam bank',
    study: 'Study guides',
    faq: 'Course FAQ',
  } satisfies Record<MaterialKind, string>,
  lesson: (n: number) => `Lesson ${n}`,
  lessons: 'Lessons',
  /** A table column in which each row is one lesson. */
  lessonColumn: 'Lesson',
  minutes: (n: number) => `${n} min`,
  audience: 'Audience',
  length: 'Length',
  lengthValue: (lessons: number, minutes: number) => `${lessons} ${lessons === 1 ? 'lesson' : 'lessons'} · ${minutes} minutes each`,
  lengthSessions: (lessons: number, sessions: string[]) => `${lessons} ${lessons === 1 ? 'lesson' : 'lessons'} · each ${sessions.join(' + ')}`,
  sessionKinds: { class: 'Class', lecture: 'Lecture', seminar: 'Seminar', lab: 'Lab', problems: 'Problem class' } as Record<SessionKind, string>,
  sessionHeading: (kind: string, minutes: number) => `${kind} · ${minutes} min`,
  sessionPart: (kind: string, minutes: number) => `${kind} ${minutes} min`,
  subject: 'Subject',
  objectives: 'Objectives',
  /** A table column in which each row is one objective. */
  objectiveColumn: 'Objective',
  whatYouLearn: 'What you will learn',
  schedule: 'Schedule',
  focus: 'Focus',
  reading: 'Reading',
  beforeClass: 'Before class',
  assessment: 'How learning is assessed',
  gradeItem: 'Component',
  weight: 'Weight',
  total: 'Total',
  weightsOff: (total: string) => `These weights add up to ${total}, not 100%.`,
  syllabusCheck: 'What Folio’s check found',
  syllabusCheckClean: 'Folio checked this syllabus and found nothing to fix.',
  syllabusChecking: 'Folio is checking this syllabus.',
  yourSyllabus: 'Your syllabus',
  issueKinds: { error: 'Error', missing: 'Missing', unclear: 'Unclear' },
  quizzesLine: (n: number, per: number) => `${n === 1 ? 'A short quiz' : `${n} short quizzes`}, about ${per} ${per === 1 ? 'question' : 'questions'} each`,
  assignmentLine: (title: string, n: number) => `${title} (lesson ${n})`,
  discussionsLine: (n: number) => (n === 1 ? 'A class discussion in 1 lesson' : `Class discussions in ${n} lessons`),
  policies: 'Class policies',
  keyIdeas: 'Key ideas',
  vocabulary: 'Vocabulary',
  time: 'Time',
  activity: 'Activity',
  details: 'What happens',
  teacherNote: 'Teacher note',
  steps: 'Steps',
  questions: 'Questions',
  takenInClass: 'Taken in class',
  gradedInClass: 'Graded in class',
  gradedWith: (title: string) => `Graded with: ${title}`,
  buildsToward: (what: string) => `Builds toward: ${what}`,
  dueAt: (lesson: string) => `Due at the start of: ${lesson}`,
  criterion: 'Criterion',
  followUps: 'Follow-up questions',
  answerKey: 'Answer key',
  answer: 'Answer',
  why: 'Why',
  checkYourself: 'Check yourself',
  overview: 'Overview',
  coveredIn: 'Taught in',
  assessedBy: 'Assessed by',
  questionsCount: (n: number) => (n === 1 ? '1 question' : `${n} questions`),
  none: '—',
  studentCopy: 'Student copy',
  teacherCopy: 'Teacher copy, with answers',
  trueWord: 'True',
  falseWord: 'False',
  continued: (title: string) => `${title} (continued)`,
  points: (n: number) => (n === 1 ? '1 pt' : `${n} pts`),
  general: 'General',
  module: {
    title: 'Weekly modules',
    length: (weeks: number, hours: number) => `${weeks} ${weeks === 1 ? 'week' : 'weeks'} · about ${hours} hours a week, on your own time`,
    week: (n: number) => `Week ${n}`,
    thisWeek: 'This week',
    due: 'Due',
    picture: 'Picture',
    afterYourOwn: 'Compare with this after you have written your own.',
    video: (minutes: number) => (minutes ? `Video, ${minutes} min` : 'Video'),
    file: 'File',
    transcript: 'Transcript',
    callouts: { checkpoint: 'Checkpoint', stuck: 'If it did not work', why: 'Why this works', tip: 'Tip', warning: 'Careful', version: 'Version' },
    kit: 'For the instructor',
    announcement: 'Announcement to post',
    watchFor: 'What to watch for',
    feedback: 'Feedback to adapt',
    atRisk: 'Who to contact',
    toCheck: 'To try on your own installation',
    toCheckLead: 'Written without a source of yours to go by, so it may not match your version. Try each one before the week opens.',
    toMake: 'To make before the week opens',
    toMakeLead: 'Each picture, recording and file this page asks for, in page order, with what it must show. Capture each one in the state its step leaves, before any later step, and check it against the step once it is made.',
    where: (part: string, step: number) => (step ? `${part}, after step ${step}` : part),
    clip: 'Screen recording',
    withFile: (text: string, name: string) => `${text} (file: ${name})`,
  },
};

export type DocLabels = typeof en;

const zh: DocLabels = {
  materials: {
    map: '目标与考核',
    syllabus: '教学大纲',
    plan: '教案',
    slides: '课件',
    assignments: '作业',
    rubrics: '评分标准',
    discussions: '课堂讨论',
    quiz: '测验与题库',
    study: '学习指南',
    faq: '课程问答',
  },
  lesson: (n) => `第 ${n} 课`,
  lessons: '各课',
  lessonColumn: '课',
  minutes: (n) => `${n} 分钟`,
  audience: '对象',
  length: '课数与时长',
  lengthValue: (lessons, minutes) => `共 ${lessons} 课 · 每课 ${minutes} 分钟`,
  lengthSessions: (lessons, sessions) => `共 ${lessons} 课 · 每课 ${sessions.join(' + ')}`,
  sessionKinds: { class: '课堂', lecture: '讲授', seminar: '研讨', lab: '实验', problems: '习题课' },
  sessionHeading: (kind, minutes) => `${kind} · ${minutes} 分钟`,
  sessionPart: (kind, minutes) => `${kind} ${minutes} 分钟`,
  subject: '学科',
  objectives: '学习目标',
  objectiveColumn: '学习目标',
  whatYouLearn: '你将学到',
  schedule: '教学进度',
  focus: '重点',
  reading: '课前阅读',
  beforeClass: '课前阅读',
  assessment: '考核方式',
  gradeItem: '考核项目',
  weight: '占比',
  total: '合计',
  weightsOff: (total) => `各项占比合计为 ${total}，而不是 100%。`,
  syllabusCheck: 'Folio 检查发现的问题',
  syllabusCheckClean: 'Folio 检查了这份教学大纲，没有发现需要修改的地方。',
  syllabusChecking: 'Folio 正在检查这份教学大纲。',
  yourSyllabus: '你的教学大纲',
  issueKinds: { error: '错误', missing: '缺少', unclear: '不清楚' },
  quizzesLine: (n, per) => `${n} 次测验，每次约 ${per} 题`,
  assignmentLine: (title, n) => `${title}（第 ${n} 课）`,
  discussionsLine: (n) => `有 ${n} 课包含课堂讨论`,
  policies: '课堂规则',
  keyIdeas: '核心概念',
  vocabulary: '关键词',
  time: '时间',
  activity: '环节',
  details: '内容',
  teacherNote: '教师提示',
  steps: '步骤',
  questions: '题目',
  takenInClass: '课堂完成',
  gradedInClass: '课堂评分',
  gradedWith: (title) => `评分依据：${title}`,
  buildsToward: (what) => `最终作业：${what}`,
  dueAt: (lesson) => `上交时间：${lesson} 开始时`,
  criterion: '评分项',
  followUps: '追问',
  answerKey: '答案与解析',
  answer: '答案',
  why: '解析',
  checkYourself: '自我检测',
  overview: '概要',
  coveredIn: '在哪一课',
  assessedBy: '用什么考核',
  questionsCount: (n) => `${n} 道题`,
  none: '—',
  studentCopy: '学生版',
  teacherCopy: '教师版（含答案）',
  trueWord: '正确',
  falseWord: '错误',
  continued: (title: string) => `${title}（续）`,
  points: (n) => `${n} 分`,
  general: '通用',
  module: {
    title: '每周模块',
    length: (weeks, hours) => `${weeks} 周 · 每周约 ${hours} 小时，自定时间`,
    week: (n) => `第 ${n} 周`,
    thisWeek: '本周任务',
    due: '截止',
    picture: '图片',
    afterYourOwn: '写完自己的之后，再与下面的对照。',
    video: (minutes) => (minutes ? `视频（${minutes} 分钟）` : '视频'),
    file: '文件',
    transcript: '文字稿',
    callouts: { checkpoint: '检查点', stuck: '如果没有成功', why: '为什么这样可行', tip: '提示', warning: '注意', version: '版本' },
    kit: '教师用',
    announcement: '本周公告',
    watchFor: '需要留意',
    feedback: '反馈参考',
    atRisk: '需要联系的学生',
    toCheck: '请在自己的软件里试一遍',
    toCheckLead: '以下内容没有您提供的资料可依据，可能与您的版本不一致。请在开课前逐条试一遍。',
    toMake: '开课前需要制作',
    toMakeLead: '本页要求的每张图片、每段录屏和每个文件，按页面顺序列出，并说明应展示的内容。请在对应步骤刚完成、后续步骤尚未进行时截取，做好后对照该步骤检查一遍。',
    where: (part, step) => (step ? `${part}，第 ${step} 步之后` : part),
    clip: '录屏',
    withFile: (text, name) => `${text}（文件：${name}）`,
  },
};

export function docLabels(language: Language): DocLabels {
  return language === 'zh-CN' ? zh : en;
}

/** The words for one course: a course taught online on the students' own time counts weeks, and its plans are module pages. */
export function courseLabels(course: { language: Language; delivery?: string }): DocLabels {
  const l = docLabels(course.language);
  if (course.delivery !== 'online-async' && course.delivery !== 'online-mixed') return l;
  return { ...l, lesson: l.module.week, materials: { ...l.materials, plan: l.module.title } };
}
