/**
 * What a module page is told when its week teaches a tool, software or code: its parts are tutorials a student
 * follows alone, so every rule here is one a student was stopped by when it was missing.
 */
export const HANDS_ON = [
  'When the week teaches a tool, software or code, the parts are a tutorial the student follows on their own computer: each part is titled with what gets done ("Make the player move"), opens with one sentence of why, then gives numbered steps of one action each. A scene, file or object the student makes is given a name when it is made, and called by it afterwards. A step says where before what ("In the Hierarchy window, right-click…"), names every button, menu and field in bold exactly as the screen shows it (**Add Component**), gives menu paths with ">", and gives exact values. A step that presses Play to test something ends by stopping Play: nothing is built or edited with Play on. Every part ends with a "checkpoint" callout: what the student should now see, and what it looks like when it went wrong. After a part where things commonly fail, a "stuck" callout lists the two or three likely causes, with the fix. An error message is quoted, and what the tool does when something is wrong is stated (which line it reports, which message it shows), only as the teacher\'s sources give it; otherwise say what to look for in general terms (a red entry that names a file and a line) and have the student read their own. A short "why" callout may explain what a step did; the steps themselves stay bare.',
  'Code longer than one line goes in a block of type "code", placed straight after the step that says to type it: end the steps block there and start a new one after the code, so nobody scrolls past later steps to find it. It holds the whole file when it is new, or the lines to add with a line of the file above and below them, exactly as typed, with comments a beginner can read. Explain new code after the block, line by line where it is the first time. When a file an earlier step or week wrote is replaced whole, the new version still does everything the old one did, or the page says what was taken out and why. Inline backticks are for names and single lines.',
  // Told what Folio runs on, a writer showed "3 14" under a version check and, under it, "this cell should print 3 12".
  // Without it, one week in two came with its Python inside the steps or in blocks with no kind, and nothing could be run.
  'Python a student runs in a notebook is always a block of type "code" and kind "python": one block for each cell, in the order they are run, a one-line cell too, never inside a step\'s text. What a cell prints follows in a block of kind "output", exactly as printed. Folio runs these blocks in order, each week in a fresh notebook with no network, on Python 3.14 with pandas 3.0, NumPy 2.4, Matplotlib 3.10, SciPy 1.18, statsmodels 0.14 and scikit-learn 1.8, and the page shows what they really print and draw: so a week\'s code runs from its own first cell, makes its data in a cell (or writes the file it then reads), and uses nothing that those versions, or the versions the course names, have removed or renamed. Ask for no picture of a cell\'s output or of its chart: Folio places them. Under a cell that asks the machine about itself (which Python, which version of a library), write what the student\'s machine prints, set up as the page sets it up: the versions the course names, never Folio\'s.',
  'The page is rich in pictures: a beginner checks their screen against them. Ask for a screenshot ("shots" on a steps block, or an "image" block) wherever the thing to click is hard to find, a window or setting must look a certain way, or a result can be seen: usually two to four in a part, and one of the result at every checkpoint. Where something moves or runs (pressing Play, a drag, flying the view), ask for a "video" of kind "clip": a silent recording of the screen under a minute, with "alt" saying what happens in it; and open the week with a picture or clip of what will be built. A screenshot goes under the step that produces what it shows, never an earlier one. One picture shows one window in one state: a drag, or anything that changes, is a clip, and a clip is framed to hold everything it is said to show. Under "shows", write for the person who captures it: which one window, in the state that step leaves and nothing a later step adds, with which names and values visible, what to outline, and on which system when Windows and Mac differ. An image or video\'s "text" is its caption: one line telling the student what to compare with their own screen. Under "alt", give what a student needs from the picture (the names and values in it), never "a screenshot of…". Never refer to a picture as if the student could not go on without it, and never tell the student to take or look at "the screenshot below": the words carry the step.',
  'Names of buttons, menus, fields and windows are taken from the teacher\'s sources when they give them, exactly, and never from memory where the two differ; what a new project or a window holds is described as the sources describe it. Never identify something by its color alone ("the green arrow, which points up"), and where a result is judged by color, give a name or value to confirm it by. Give the menu, keyboard or trackpad way beside a drag, a mouse wheel or a right-click where there is one. A step relies only on actions an earlier step or week taught (renaming, duplicating and deleting count), or teaches them. A new project starts from the tool\'s defaults, not as last week\'s project was left. A project carried on from earlier weeks is as those weeks left it: open it by the names they gave, and where something they left would be in the way of this week\'s work (an object where the new one goes, a camera elsewhere), a step moves or removes it. Values the student types use keyboard characters: a hyphen for a minus. Anything done outside the tool itself (taking a screenshot, recording the screen, finding, zipping or unzipping a folder) is given in full for Windows and for Mac the first time it is needed; a later week names the week and part that taught it.',
  'Name the exact version and template the page is written for in a "version" callout in the first part, with what to do when the student\'s differs. Give a "file" block for what the student starts from (starter) and for the project as it should stand at the end of the week (checkpoint), so one failure does not block the week: its "text" is the file\'s name and nothing more (Dodge-week6-start.zip), and "shows" says what it holds; beside each, say where to unzip it so that it does not replace the student\'s own project, and how to open it.',
  'After the guided parts, a part with a challenge the student does without steps: one a little beyond the tutorial and one further, marked optional, each stated as what the result does and tried out in your head against what the student has built, with a hint in a "tip" callout. A result that cannot be worked out on paper (how bright, how bouncy, how fast) is asked for only with settings the sources give.',
].join(' ');
