/**
 * What a module page is told when its week teaches a tool, software or code: its parts are tutorials a student
 * follows alone, so every rule here is one a student was stopped by when it was missing.
 */
export const HANDS_ON = [
  'When the week teaches a tool, software or code, the parts are a tutorial the student follows on their own computer: each part is titled with what gets done ("Make the player move"), opens with one sentence of why, then gives numbered steps of one action each. A scene, file or object the student makes is given a name when it is made, and called by it afterwards. A step says where before what ("In the Hierarchy window, right-click…"), names every button, menu and field in bold exactly as the screen shows it (**Add Component**), gives menu paths with ">", and gives exact values. Every part ends with a "checkpoint" callout: what the student should now see, and what it looks like when it went wrong. After a part where things commonly fail, a "stuck" callout lists the two or three likely causes, with the exact error text when there is one, and the fix. A short "why" callout may explain what a step did; the steps themselves stay bare.',
  'Code longer than one line goes in a block of type "code": the whole file when it is new, or the lines to add with a line of the file above and below them, exactly as typed, with comments a beginner can read. Explain new code after the block, line by line where it is the first time. Inline backticks are for names and single lines.',
  'The page is rich in pictures: a beginner checks their screen against them. Ask for a screenshot ("shots" on a steps block, or an "image" block) wherever the thing to click is hard to find, a window or setting must look a certain way, or a result can be seen: usually two to four in a part, and one of the result at every checkpoint. Where something moves or runs (pressing Play, a drag, flying the view), ask for a "video" of kind "clip": a silent recording of the screen under a minute, with "alt" saying what happens in it; and open the week with a picture or clip of what will be built. A screenshot goes under the step that produces what it shows, never an earlier one. One picture shows one window in one state: a drag, or anything that changes, is a clip, and a clip is framed to hold everything it is said to show. Under "shows", write for the person who captures it: which one window, in what state, with which names and values visible, what to outline, and on which system when Windows and Mac differ. An image or video\'s "text" is its caption: one line telling the student what to compare with their own screen. Under "alt", give what a student needs from the picture (the names and values in it), never "a screenshot of…". Never refer to a picture as if the student could not go on without it: the words carry the step.',
  'Names of buttons, menus, fields and windows are taken from the teacher\'s sources when they give them, exactly, and never from memory where the two differ; what a new project or a window holds is described as the sources describe it. Never identify something by its color alone ("the green arrow, which points up"), and where a result is judged by color, give a name or value to confirm it by. Give the menu, keyboard or trackpad way beside a drag, a mouse wheel or a right-click where there is one. A step relies only on actions an earlier step or week taught (renaming, duplicating and deleting count), or teaches them. A new project starts from the tool\'s defaults, not as last week\'s project was left. Values the student types use keyboard characters: a hyphen for a minus. Anything done outside the tool itself (taking a screenshot, recording the screen, finding, zipping or unzipping a folder) is given in full for Windows and for Mac the first time it is needed; a later week names the week and part that taught it.',
  'Name the exact version and template the page is written for in a "version" callout in the first part, with what to do when the student\'s differs. Give a "file" block for what the student starts from (starter) and for the project as it should stand at the end of the week (checkpoint), so one failure does not block the week; beside each, say where to unzip it so that it does not replace the student\'s own project, and how to open it.',
  'After the guided parts, a part with a challenge the student does without steps: one a little beyond the tutorial and one further, marked optional, each stated as what the result does and tried out in your head against what the student has built, with a hint in a "tip" callout. A result that cannot be worked out on paper (how bright, how bouncy, how fast) is asked for only with settings the sources give.',
].join(' ');
